/**
 * Single source of truth for site-wide SEO + business data.
 * Used by metadata builders, JSON-LD schema, breadcrumbs and sitemap.
 */

export const SITE_URL = 'https://safeaiafrica.com'

export const SITE_NAME = 'SAFE AI-AFRICA'

export const SITE_TAGLINE = 'Empowering Africa Through Responsible Artificial Intelligence'

/** Default social share image (1200x630, generated by src/app/og-image/route.tsx). */
export const DEFAULT_OG_IMAGE = '/og-image'

export const BUSINESS = {
  legalName: 'SAFE AI-AFRICA',
  email: 'safeaiafrica@gmail.com',
  phone: '+256775323200',
  phoneDisplay: '+256 775 323 200',
  altPhone: '+256756985966',
  altPhoneDisplay: '+256 756 985 966',
  whatsapp: 'https://wa.me/256775323200',
  addressLocality: 'Kampala',
  addressRegion: 'Central Region',
  addressCountry: 'UG',
  addressCountryName: 'Uganda',
  latitude: 0.3476,
  longitude: 32.5825,
  foundingDate: '2023',
  /** Published response-time promise, reused across CTAs, forms and schema. */
  responseTimeHours: 24,
  responseTimePromise: 'We reply to every message within 24 hours, Monday to Sunday.',
  openingHours: [
    { days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], opens: '08:00', closes: '18:00' },
    { days: ['Saturday'], opens: '09:00', closes: '14:00' },
  ],
} as const

export const MAPS = {
  /** Keyless Google Maps embed for the Kampala head office. */
  embedUrl:
    'https://www.google.com/maps?q=Kampala,+Uganda&hl=en&z=12&output=embed',
  directionsUrl:
    'https://www.google.com/maps/dir/?api=1&destination=Kampala%2C+Uganda',
  placeUrl: 'https://www.google.com/maps/place/Kampala,+Uganda',
} as const

export const SOCIAL_PROFILES = [
  'https://www.facebook.com/safeaiafrica',
  'https://www.instagram.com/safe.aiafrica/',
  'https://x.com/safeaiafrica',
  'https://www.linkedin.com/company/safe-ai-africa',
  'https://www.tiktok.com/@safe.ai.africa',
]

export const PRODUCT_SITES = [
  'https://safeseq.safeaiafrica.com',
  'https://safekemia.safeaiafrica.com',
  'https://invoicemasterpro.safeaiafrica.com',
  'https://safelytics.safeaiafrica.com',
  'https://safefoodmanager.safeaiafrica.com',
  'https://safeuzazi.safeaiafrica.com',
]

/** Absolute URL helper, because schema.org and OG tags need absolute URLs. */
export function absoluteUrl(path = '/'): string {
  if (path.startsWith('http')) return path
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`
}
